// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCns_bHOJImYNpPVK-3GNCL00J4oFFZJo',
    appId: '1:842811367433:web:3a50734cdd9f09c2c4d8d8',
    messagingSenderId: '842811367433',
    projectId: 'notes-app-5671f',
    authDomain: 'notes-app-5671f.firebaseapp.com',
    storageBucket: 'notes-app-5671f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCb-_3lP7N1piHEu7PL1w9O-Ey9qPmaY',
    appId: '1:842811367433:android:7f3db899c9c2ca76c4d8d8',
    messagingSenderId: '842811367433',
    projectId: 'notes-app-5671f',
    storageBucket: 'notes-app-5671f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDjqDQ3Ggo6K5okhpHwGPK-YZXy_IE-I',
    appId: '1:842811367433:ios:feb550538c5907ddc4d8d8',
    messagingSenderId: '842811367433',
    projectId: 'notes-app-5671f',
    storageBucket: 'notes-app-5671f.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXDjqDQ3Ggo6K5okhpHwGPK-YZXy_IE-I',
    appId: '1:842811367433:ios:feb550538c5907ddc4d8d8',
    messagingSenderId: '842811367433',
    projectId: 'notes-app-5671f',
    storageBucket: 'notes-app-5671f.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssJqgs3npQzZqn9chWyeIEMAtkgoAcwU',
    appId: '1:842811367433:web:cbfbe86011e3c239c4d8d8',
    messagingSenderId: '842811367433',
    projectId: 'notes-app-5671f',
    authDomain: 'notes-app-5671f.firebaseapp.com',
    storageBucket: 'notes-app-5671f.firebasestorage.app',
  );
}
